import React from 'react';
import { User, UserRole, TicketType, TicketStatus, EmailStatus, SubticketStatus, UploadedRecord, Permissions } from './types';

export const SUPERUSER_PERMISSIONS: Permissions = {
    dashboard: { view: true, configure: true },
    tickets: { view: true, create: true, edit: true, delete: true },
    mail: { view: true },
    cargas: { view: true, configure: true },
    archived: { view: true, edit: true },
    sql: { view: true },
    userManagement: { view: true, create: true, edit: true, delete: true },
};

export const USER_PERMISSIONS: Permissions = {
    dashboard: { view: true, configure: false },
    tickets: { view: true, create: true, edit: true, delete: false },
    mail: { view: true },
    cargas: { view: true, configure: false },
    archived: { view: false, edit: false },
    sql: { view: false },
    userManagement: { view: false, create: false, edit: false, delete: false },
};


export const USERS: User[] = [
    { 
        id: 'user1', 
        name: 'Diego', 
        role: UserRole.Superuser, 
        password: 'superuser123', 
        permissions: {
            tickets: { view: true, create: true, edit: true, delete: true },
            dashboard: { view: true, configure: true },
            userManagement: { view: true, create: true, edit: true, delete: true },
            cargas: { view: true, configure: true },
            archived: { view: true, edit: true },
            mail: { view: true },
            sql: { view: true }
        }
    },
    { id: 'user2', name: 'Frank T.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user3', name: 'Oscar C.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user4', name: 'Gina L.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user5', name: 'Manuel J.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user6', name: 'Selena C.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user7', name: 'Kenneth N.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user8', name: 'Paul C.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user9', name: 'Lucero R.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user10', name: 'Maricielo J.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user11', name: 'Krystel R.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user12', name: 'Marco R.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user13', name: 'Max C.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user14', name: 'Jean M.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS },
    { id: 'user15', name: 'Miguel Y.', role: UserRole.User, password: 'user123', permissions: USER_PERMISSIONS }
];

export const TICKET_TYPES = Object.values(TicketType);


export const REPORTED_BY_OPTIONS = [
    'ATM_PROACTIVO',
    'ATC',
    'VT',
    'PEXT',
    'NOC',
    'MAYORISTA'
];


export const DIAGNOSIS_OPTIONS = [
    'CTO_SIN_POTENCIA',
    'CTO_DEGRADADA',
    'CTO_PUERTOS_SIN_POTENCIA',
    'CTO_PUERTOS_DEGRADADOS',
    'CTO_INTERMITENCIA',
    'LOS',
    'NAP_SIN_POTENCIA',
    'NAP_DEGRADADA',
    'NAP_PUERTOS_SIN_POTENCIA',
    'NAP_PUERTOS_DEGRADADOS',
    'CTO_DESPRENDIDA',
    'NAP_DESPRENDIDA',
    'CTO_SIN_FACTIBILIDAD'
];
export const NODE_OPTIONS = ['Chancay', 'Barranco', 'Benvenutto', 'Camana', 'Chorrillos II', 'Mirables', 'El Sauce', 'Esperanza', 'Francisco Moreyra', 'Gerardo Unger', 'Krumdieck', 'Lince', 'Los Alamos', 'Punta Hermosa', 'Los Flamengos', 'Los Jardines', 'Huandoy', 'Los Pelitres', 'Mariategui', 'Piura Catacaos', 'Natalio Sanchez', 'Arriola', 'Pershing', 'Rep. de Panama', 'Salamanca', 'San Luis', 'Santa Rosa', 'Tres de Mayo', 'Uruguay', 'Vitarte', 'Todos los Nodos', 'Ninguno', 'Trigal', 'Niño Jesús', 'Barlovento', 'Sucre', 'Core Krumdieck', 'Core Galvez', 'Santa Catalina', 'NovaCloud', 'La Molina', 'Pachacamac', '200 Millas'
];
export const OLT_OPTIONS = ["OLT0_X15_FRANCISCO_MOREYRA", "OLT0_X15_REP_PANAMA", "OLT2_MA5800_X15_TRUJILLO_LARCO", "OLT1_MA5800_X15_ANGAMOSII", "OLT3_MA5800_X2_BENVENUTTO", "OLT1_GALVEZ-II", "OLT2_MA5800_X15_SAN_LUIS", "OLT1_JUAN-PABLO", "OLT1_ALAMOS_X15", "OLT0_NINO_JESUS"];
export const CITY_OPTIONS = ['Lima', 'Callao', 'San Miguel', 'Barranco',"Surco","Miraflores", "Pueblo Libre","Breña"];
export const ROOT_CAUSE_OPTIONS = ['Corte de Fibra', 'Falla de Potencia', 'Equipo Dañado'];
export const SOLUTION_OPTIONS = ['Fusión de Fibra', 'Reemplazo de SFP', 'Reinicio de Equipo'];
export const STATUS_POST_SLA_OPTIONS = ['Dentro de SLA', 'Fuera de SLA'];
export const EVENT_RESPONSIBLE_OPTIONS = ['Equipo de Campo', 'Proveedor Externo', 'Infraestructura'];
export const PAUSE_REASON_OPTIONS = ['Falta de personal', 'A la espera de repuestos', 'Condiciones climáticas adversas', 'Permisos pendientes'];

export const MANDATORY_CARGAS_COLUMNS = ['sn', 'cto', 'ticket'];

export const initialTickets = [
    {
        id: 't1',
        code: 'W_CR_000001_P',
        type: TicketType.Proactive,
        reportedBy: 'Monitoreo Automático',
        initialDiagnosis: 'Falla de Fibra',
        creationDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: true,
        node: 'Nodo Central',
        olt: 'OLT A-1',
        advisor: 'Diego',
        emailStatus: EmailStatus.NotDeclared,
        status: TicketStatus.Pending,
        subticketIds: ['st1', 'st2'],
        pauseHistory: [],
        executionHistory: [],
    },
    {
        id: 't2',
        code: 'W_CR_000002_R',
        type: TicketType.Reactive,
        reportedBy: 'Cliente A',
        initialDiagnosis: 'Problema de Equipo',
        creationDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: false,
        node: 'Nodo Norte',
        olt: 'OLT B-2',
        advisor: 'Pedro',
        emailStatus: EmailStatus.Declared,
        status: TicketStatus.Solved,
        closingDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        subticketIds: ['st3'],
        pauseHistory: [],
        executionHistory: [],
    },
     {
        id: 't3',
        code: 'W_CR_000003_M',
        type: TicketType.Maintenance,
        reportedBy: 'Equipo Interno',
        initialDiagnosis: 'Mantenimiento Programado',
        creationDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: true,
        node: 'Nodo Sur',
        olt: 'OLT C-3',
        advisor: 'María',
        emailStatus: EmailStatus.NotDeclared,
        status: TicketStatus.Pending,
        subticketIds: [],
        pauseHistory: [],
        executionHistory: [],
    },
    {
      id: 't4',
      code: 'W_CR_000004_R',
      type: TicketType.Reactive,
      reportedBy: 'ATC',
      initialDiagnosis: 'LOS',
      creationDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      serviceUnavailable: true,
      node: 'Lince',
      olt: 'OLT1_MA5800_X15_ANGAMOSII',
      advisor: 'Oscar C.',
      emailStatus: EmailStatus.Declared,
      status: TicketStatus.InProgress,
      subticketIds: ['st4'],
      pauseHistory: [],
      executionHistory: [{ startTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() }],
    },
    {
      id: 't5',
      code: 'W_CR_000005_P',
      type: TicketType.Proactive,
      reportedBy: 'PEXT',
      initialDiagnosis: 'CTO sin potencia',
      creationDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      serviceUnavailable: true,
      node: 'Francisco Moreyra',
      olt: 'OLT0_X15_FRANCISCO_MOREYRA',
      advisor: 'Gina L.',
      emailStatus: EmailStatus.Declared,
      status: TicketStatus.Solved,
      closingDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      subticketIds: ['st5'],
      pauseHistory: [],
      executionHistory: [],
    },
    {
      id: 't6',
      code: 'W_CR_000006_R',
      type: TicketType.Reactive,
      reportedBy: 'VT',
      initialDiagnosis: 'CTO degradada',
      creationDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      serviceUnavailable: false,
      node: 'Barranco',
      olt: 'OLT3_MA5800_X2_BENVENUTTO',
      advisor: 'Manuel J.',
      emailStatus: EmailStatus.NotDeclared,
      status: TicketStatus.OnHold,
      subticketIds: ['st6'],
      pauseHistory: [{ startTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), reason: 'A la espera de repuestos' }],
      executionHistory: [],
    },
    {
      id: 't7',
      code: 'W_CR_000007_M',
      type: TicketType.Maintenance,
      reportedBy: 'NOC',
      initialDiagnosis: 'Caja NAP sin potencia',
      creationDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      serviceUnavailable: true,
      node: 'San Luis',
      olt: 'OLT2_MA5800_X15_SAN_LUIS',
      advisor: 'Selena C.',
      emailStatus: EmailStatus.Declared,
      status: TicketStatus.Solved,
      closingDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      subticketIds: ['st7'],
      pauseHistory: [],
      executionHistory: [],
    },
    {
      id: 't8',
      code: 'W_CR_000008_P',
      type: TicketType.Proactive,
      reportedBy: 'ATM Proactivo',
      initialDiagnosis: 'CTO con intermitencia',
      creationDate: new Date().toISOString(),
      serviceUnavailable: false,
      node: 'Los Alamos',
      olt: 'OLT1_ALAMOS_X15',
      advisor: 'Kenneth N.',
      emailStatus: EmailStatus.NotDeclared,
      status: TicketStatus.Pending,
      subticketIds: ['st8'],
      pauseHistory: [],
      executionHistory: [],
    },
    {
      id: 't9',
      code: 'W_CR_000009_R',
      type: TicketType.Reactive,
      reportedBy: 'ATC',
      initialDiagnosis: 'LOS',
      creationDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      serviceUnavailable: true,
      node: 'Rep. de Panama',
      olt: 'OLT0_X15_REP_PANAMA',
      advisor: 'Paul C.',
      emailStatus: EmailStatus.NotDeclared,
      status: TicketStatus.InProgress,
      subticketIds: ['st9', 'st10'],
      pauseHistory: [],
      executionHistory: [{ startTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() }],
    },
    {
      id: 't10',
      code: 'W_CR_000010_P',
      type: TicketType.Proactive,
      reportedBy: 'PEXT',
      initialDiagnosis: 'CTO con puertos degradados',
      creationDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      serviceUnavailable: false,
      node: 'Niño Jesús',
      olt: 'OLT0_NINO_JESUS',
      advisor: 'Lucero R.',
      emailStatus: EmailStatus.Declared,
      status: TicketStatus.Solved,
      closingDate: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
      subticketIds: ['st11'],
      pauseHistory: [],
      executionHistory: [],
    },
    {
      id: 't11',
      code: 'W_CR_000011_M',
      type: TicketType.Maintenance,
      reportedBy: 'Equipo Interno',
      initialDiagnosis: 'Caja NAP desprendida',
      creationDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      serviceUnavailable: true,
      node: 'Pachacamac',
      olt: 'OLT1_MA5800_X15_ANGAMOSII',
      advisor: 'Maricielo J.',
      emailStatus: EmailStatus.NotDeclared,
      status: TicketStatus.Pending,
      subticketIds: [],
      pauseHistory: [],
      executionHistory: [],
    },
    {
      id: 't12',
      code: 'W_CR_000012_R',
      type: TicketType.Reactive,
      reportedBy: 'Mayorista',
      initialDiagnosis: 'CTO desprendida',
      creationDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      serviceUnavailable: true,
      node: 'La Molina',
      olt: 'OLT2_MA5800_X15_SAN_LUIS',
      advisor: 'Krystel R.',
      emailStatus: EmailStatus.Declared,
      status: TicketStatus.InProgress,
      subticketIds: ['st12'],
      pauseHistory: [{ startTime: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(), endTime: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), reason: 'Permisos pendientes' }],
      executionHistory: [{ startTime: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString() }],
    },
    {
        id: 't13',
        code: 'W_CR_000013_P',
        type: TicketType.Proactive,
        reportedBy: 'ATM Proactivo',
        initialDiagnosis: 'CTO sin potencia',
        creationDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: true,
        node: 'Trigal',
        olt: 'OLT1_GALVEZ-II',
        advisor: 'Marco R.',
        emailStatus: EmailStatus.Declared,
        status: TicketStatus.Solved,
        closingDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        subticketIds: ['st13'],
        pauseHistory: [],
        executionHistory: [],
    },
    {
        id: 't14',
        code: 'W_CR_000014_R',
        type: TicketType.Reactive,
        reportedBy: 'ATC',
        initialDiagnosis: 'LOS',
        creationDate: new Date(Date.now() - 1 * 12 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: true,
        node: 'Sucre',
        olt: 'OLT0_X15_FRANCISCO_MOREYRA',
        advisor: 'Max C.',
        emailStatus: EmailStatus.NotDeclared,
        status: TicketStatus.Pending,
        subticketIds: ['st14'],
        pauseHistory: [],
        executionHistory: [],
    },
    {
        id: 't15',
        code: 'W_CR_000015_M',
        type: TicketType.Maintenance,
        reportedBy: 'NOC',
        initialDiagnosis: 'Mantenimiento Programado',
        creationDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: false,
        node: 'Santa Catalina',
        olt: 'OLT0_X15_REP_PANAMA',
        advisor: 'Jean M.',
        emailStatus: EmailStatus.Declared,
        status: TicketStatus.OnHold,
        subticketIds: [],
        pauseHistory: [{ startTime: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), reason: 'Condiciones climáticas adversas' }],
        executionHistory: [],
    },
    {
        id: 't16',
        code: 'W_CR_000016_P',
        type: TicketType.Proactive,
        reportedBy: 'PEXT',
        initialDiagnosis: 'CTO con puertos sin potencia',
        creationDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: true,
        node: 'Core Krumdieck',
        olt: 'OLT1_MA5800_X15_ANGAMOSII',
        advisor: 'Miguel Y.',
        emailStatus: EmailStatus.Declared,
        status: TicketStatus.Solved,
        closingDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        subticketIds: ['st15', 'st16'],
        pauseHistory: [],
        executionHistory: [],
    },
    {
        id: 't17',
        code: 'W_CR_000017_R',
        type: TicketType.Reactive,
        reportedBy: 'VT',
        initialDiagnosis: 'Caja NAP con puertos degradados',
        creationDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: false,
        node: 'Barlovento',
        olt: 'OLT3_MA5800_X2_BENVENUTTO',
        advisor: 'Diego',
        emailStatus: EmailStatus.NotDeclared,
        status: TicketStatus.Pending,
        subticketIds: ['st17'],
        pauseHistory: [],
        executionHistory: [],
    },
    {
        id: 't18',
        code: 'W_CR_000018_P',
        type: TicketType.Proactive,
        reportedBy: 'ATM Proactivo',
        initialDiagnosis: 'CTO degradada',
        creationDate: new Date(Date.now() - 2 * 12 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: false,
        node: '200 Millas',
        olt: 'OLT2_MA5800_X15_SAN_LUIS',
        advisor: 'Oscar C.',
        emailStatus: EmailStatus.NotDeclared,
        status: TicketStatus.InProgress,
        subticketIds: ['st18'],
        pauseHistory: [],
        executionHistory: [{ startTime: new Date(Date.now() - 1 * 12 * 60 * 60 * 1000).toISOString() }],
    },
    {
        id: 't19',
        code: 'W_CR_000019_R',
        type: TicketType.Reactive,
        reportedBy: 'Cliente B',
        initialDiagnosis: 'LOS',
        creationDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: true,
        node: 'Chorrillos II',
        olt: 'OLT1_ALAMOS_X15',
        advisor: 'Gina L.',
        emailStatus: EmailStatus.Declared,
        status: TicketStatus.Solved,
        closingDate: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
        subticketIds: ['st19'],
        pauseHistory: [],
        executionHistory: [],
    },
    {
        id: 't20',
        code: 'W_CR_000020_M',
        type: TicketType.Maintenance,
        reportedBy: 'Equipo Interno',
        initialDiagnosis: 'CTO sin factibilidad para hacer trabajos',
        creationDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: false,
        node: 'Huandoy',
        olt: 'OLT0_NINO_JESUS',
        advisor: 'Manuel J.',
        emailStatus: EmailStatus.NotDeclared,
        status: TicketStatus.Pending,
        subticketIds: [],
        pauseHistory: [],
        executionHistory: [],
    },
    {
        id: 't21',
        code: 'W_CR_000021_R',
        type: TicketType.Reactive,
        reportedBy: 'ATC',
        initialDiagnosis: 'CTO sin potencia',
        creationDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: true,
        node: 'Gerardo Unger',
        olt: 'OLT1_GALVEZ-II',
        advisor: 'Selena C.',
        emailStatus: EmailStatus.NotDeclared,
        status: TicketStatus.Pending,
        subticketIds: ['st20'],
        pauseHistory: [],
        executionHistory: [],
    },
    {
        id: 't22',
        code: 'W_CR_000022_P',
        type: TicketType.Proactive,
        reportedBy: 'Monitoreo Automático',
        initialDiagnosis: 'Caja NAP sin potencia',
        creationDate: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: true,
        node: 'El Sauce',
        olt: 'OLT0_X15_FRANCISCO_MOREYRA',
        advisor: 'Kenneth N.',
        emailStatus: EmailStatus.Declared,
        status: TicketStatus.Solved,
        closingDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        subticketIds: ['st21'],
        pauseHistory: [],
        executionHistory: [],
    },
    {
        id: 't23',
        code: 'W_CR_000023_R',
        type: TicketType.Reactive,
        reportedBy: 'NOC',
        initialDiagnosis: 'LOS',
        creationDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        serviceUnavailable: true,
        node: 'Mirables',
        olt: 'OLT0_X15_REP_PANAMA',
        advisor: 'Paul C.',
        emailStatus: EmailStatus.Declared,
        status: TicketStatus.InProgress,
        subticketIds: ['st22', 'st23'],
        pauseHistory: [],
        executionHistory: [{ startTime: new Date(Date.now() - 1 * 20 * 60 * 60 * 1000).toISOString() }],
    }
];

export const initialSubtickets = [
    {
        id: 'st1',
        ticketId: 't1',
        code: 'W_CR_000001_P_1',
        cto: 'CTO-0203-LA-NE',
        card: '1',
        port: '3',
        city: 'Guadalajara',
        clientCount: 50,
        eventStartDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 3600000).toISOString(),
        creator: 'Diego',
        status: SubticketStatus.Pending,
        node: 'Nodo Central',
        olt: 'OLT A-1',
        initialDiagnosis: 'Falla de Fibra',
    },
    {
        id: 'st2',
        ticketId: 't1',
        code: 'W_CR_000001_P_2',
        cto: 'CTO-0204-LA-SW',
        card: '2',
        port: '1',
        city: 'Monterrey',
        clientCount: 25,
        eventStartDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 3600000).toISOString(),
        creator: 'Diego',
        status: SubticketStatus.Pending,
        node: 'Nodo Central',
        olt: 'OLT A-1',
        initialDiagnosis: 'Falla de Fibra',
    },
    {
        id: 'st3',
        ticketId: 't2',
        code: 'W_CR_000002_R_1',
        cto: 'CTO-0101-NY-NE',
        card: '1',
        port: '5',
        city: 'Ciudad de México',
        clientCount: 10,
        eventStartDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 3600000).toISOString(),
        creator: 'Pedro',
        status: SubticketStatus.Closed,
        node: 'Nodo Norte',
        olt: 'OLT B-2',
        initialDiagnosis: 'Problema de Equipo',
        closingAdvisor: 'Pedro',
        eventEndDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        rootCause: 'Equipo Dañado',
        badPraxis: false,
        solution: 'Reemplazo de SFP',
        eventResponsible: 'Equipo de Campo',
        comment: 'Problema resuelto.'
    },
    {
        id: 'st4',
        ticketId: 't4',
        code: 'W_CR_000004_R_1',
        cto: 'CTO-LN-001',
        card: '3',
        port: '12',
        city: 'Lima',
        clientCount: 8,
        eventStartDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Oscar C.',
        status: SubticketStatus.Pending,
        node: 'Lince',
        olt: 'OLT1_MA5800_X15_ANGAMOSII',
    },
    {
        id: 'st5',
        ticketId: 't5',
        code: 'W_CR_000005_P_1',
        cto: 'CTO-FM-002',
        card: '1',
        port: '1',
        city: 'San Borja',
        clientCount: 32,
        eventStartDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Gina L.',
        status: SubticketStatus.Closed,
        node: 'Francisco Moreyra',
        olt: 'OLT0_X15_FRANCISCO_MOREYRA',
        closingAdvisor: 'Gina L.',
        eventEndDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        rootCause: 'Corte de Fibra',
        badPraxis: false,
        solution: 'Fusión de Fibra',
        eventResponsible: 'Equipo de Campo',
    },
    {
        id: 'st6',
        ticketId: 't6',
        code: 'W_CR_000006_R_1',
        cto: 'CTO-BA-003',
        card: '5',
        port: '8',
        city: 'Barranco',
        clientCount: 15,
        eventStartDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Manuel J.',
        status: SubticketStatus.Pending,
        node: 'Barranco',
        olt: 'OLT3_MA5800_X2_BENVENUTTO',
    },
    {
        id: 'st7',
        ticketId: 't7',
        code: 'W_CR_000007_M_1',
        cto: 'NAP-SL-001',
        card: '10',
        port: '4',
        city: 'San Luis',
        clientCount: 40,
        eventStartDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Selena C.',
        status: SubticketStatus.Closed,
        node: 'San Luis',
        olt: 'OLT2_MA5800_X15_SAN_LUIS',
        closingAdvisor: 'Selena C.',
        eventEndDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        rootCause: 'Falla de Potencia',
        badPraxis: true,
        solution: 'Reinicio de Equipo',
        eventResponsible: 'Proveedor Externo',
    },
    {
        id: 'st8',
        ticketId: 't8',
        code: 'W_CR_000008_P_1',
        cto: 'CTO-LA-004',
        card: '2',
        port: '7',
        city: 'La Molina',
        clientCount: 22,
        eventStartDate: new Date().toISOString(),
        reportedToPextDate: new Date().toISOString(),
        creator: 'Kenneth N.',
        status: SubticketStatus.Pending,
        node: 'Los Alamos',
        olt: 'OLT1_ALAMOS_X15',
    },
    {
        id: 'st9',
        ticketId: 't9',
        code: 'W_CR_000009_R_1',
        cto: 'CTO-RP-005',
        card: '8',
        port: '1',
        city: 'San Isidro',
        clientCount: 18,
        eventStartDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Paul C.',
        status: SubticketStatus.Pending,
        node: 'Rep. de Panama',
        olt: 'OLT0_X15_REP_PANAMA',
    },
    {
        id: 'st10',
        ticketId: 't9',
        code: 'W_CR_000009_R_2',
        cto: 'CTO-RP-006',
        card: '8',
        port: '2',
        city: 'San Isidro',
        clientCount: 5,
        eventStartDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Paul C.',
        status: SubticketStatus.Pending,
        node: 'Rep. de Panama',
        olt: 'OLT0_X15_REP_PANAMA',
    },
    {
        id: 'st11',
        ticketId: 't10',
        code: 'W_CR_000010_P_1',
        cto: 'CTO-NJ-007',
        card: '1',
        port: '9',
        city: 'Jesús María',
        clientCount: 3,
        eventStartDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Lucero R.',
        status: SubticketStatus.Closed,
        node: 'Niño Jesús',
        olt: 'OLT0_NINO_JESUS',
        closingAdvisor: 'Lucero R.',
        eventEndDate: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        rootCause: 'Equipo Dañado',
        badPraxis: false,
        solution: 'Reemplazo de SFP',
        eventResponsible: 'Equipo de Campo',
    },
    {
        id: 'st12',
        ticketId: 't12',
        code: 'W_CR_000012_R_1',
        cto: 'CTO-LM-008',
        card: '4',
        port: '15',
        city: 'La Molina',
        clientCount: 12,
        eventStartDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Krystel R.',
        status: SubticketStatus.Pending,
        node: 'La Molina',
        olt: 'OLT2_MA5800_X15_SAN_LUIS',
    },
    {
        id: 'st13',
        ticketId: 't13',
        code: 'W_CR_000013_P_1',
        cto: 'CTO-TR-009',
        card: '11',
        port: '3',
        city: 'Surco',
        clientCount: 28,
        eventStartDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Marco R.',
        status: SubticketStatus.Closed,
        node: 'Trigal',
        olt: 'OLT1_GALVEZ-II',
        closingAdvisor: 'Marco R.',
        eventEndDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        rootCause: 'Corte de Fibra',
        badPraxis: false,
        solution: 'Fusión de Fibra',
        eventResponsible: 'Equipo de Campo',
    },
    {
        id: 'st14',
        ticketId: 't14',
        code: 'W_CR_000014_R_1',
        cto: 'CTO-SU-010',
        card: '7',
        port: '7',
        city: 'Pueblo Libre',
        clientCount: 9,
        eventStartDate: new Date(Date.now() - 1 * 12 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 1 * 12 * 60 * 60 * 1000).toISOString(),
        creator: 'Max C.',
        status: SubticketStatus.Pending,
        node: 'Sucre',
        olt: 'OLT0_X15_FRANCISCO_MOREYRA',
    },
    {
        id: 'st15',
        ticketId: 't16',
        code: 'W_CR_000016_P_1',
        cto: 'CTO-CK-011',
        card: '13',
        port: '1',
        city: 'San Isidro',
        clientCount: 14,
        eventStartDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Miguel Y.',
        status: SubticketStatus.Closed,
        node: 'Core Krumdieck',
        olt: 'OLT1_MA5800_X15_ANGAMOSII',
        closingAdvisor: 'Miguel Y.',
        eventEndDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        rootCause: 'Falla de Potencia',
        badPraxis: false,
        solution: 'Reinicio de Equipo',
        eventResponsible: 'Infraestructura',
    },
    {
        id: 'st16',
        ticketId: 't16',
        code: 'W_CR_000016_P_2',
        cto: 'CTO-CK-012',
        card: '13',
        port: '2',
        city: 'Miraflores',
        clientCount: 20,
        eventStartDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Miguel Y.',
        status: SubticketStatus.Closed,
        node: 'Core Krumdieck',
        olt: 'OLT1_MA5800_X15_ANGAMOSII',
        closingAdvisor: 'Miguel Y.',
        eventEndDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        rootCause: 'Falla de Potencia',
        badPraxis: false,
        solution: 'Reinicio de Equipo',
        eventResponsible: 'Infraestructura',
    },
    {
        id: 'st17',
        ticketId: 't17',
        code: 'W_CR_000017_R_1',
        cto: 'NAP-BV-013',
        card: '9',
        port: '5',
        city: 'Chorrillos',
        clientCount: 11,
        eventStartDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Diego',
        status: SubticketStatus.Pending,
        node: 'Barlovento',
        olt: 'OLT3_MA5800_X2_BENVENUTTO',
    },
    {
        id: 'st18',
        ticketId: 't18',
        code: 'W_CR_000018_P_1',
        cto: 'CTO-200M-014',
        card: '6',
        port: '10',
        city: 'Villa el Salvador',
        clientCount: 33,
        eventStartDate: new Date(Date.now() - 2 * 12 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 2 * 12 * 60 * 60 * 1000).toISOString(),
        creator: 'Oscar C.',
        status: SubticketStatus.Pending,
        node: '200 Millas',
        olt: 'OLT2_MA5800_X15_SAN_LUIS',
    },
    {
        id: 'st19',
        ticketId: 't19',
        code: 'W_CR_000019_R_1',
        cto: 'CTO-CH2-015',
        card: '14',
        port: '14',
        city: 'Chorrillos',
        clientCount: 7,
        eventStartDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Gina L.',
        status: SubticketStatus.Closed,
        node: 'Chorrillos II',
        olt: 'OLT1_ALAMOS_X15',
        closingAdvisor: 'Gina L.',
        eventEndDate: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
        rootCause: 'Equipo Dañado',
        badPraxis: true,
        solution: 'Reemplazo de SFP',
        eventResponsible: 'Equipo de Campo',
    },
    {
        id: 'st20',
        ticketId: 't21',
        code: 'W_CR_000021_R_1',
        cto: 'CTO-GU-016',
        card: '15',
        port: '11',
        city: 'Independencia',
        clientCount: 19,
        eventStartDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        creator: 'Selena C.',
        status: SubticketStatus.Pending,
        node: 'Gerardo Unger',
        olt: 'OLT1_GALVEZ-II',
    },
    {
        id: 'st21',
        ticketId: 't22',
        code: 'W_CR_000022_P_1',
        cto: 'NAP-ES-017',
        card: '1',
        port: '13',
        city: 'Villa María del Triunfo',
        clientCount: 45,
        eventStartDate: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Kenneth N.',
        status: SubticketStatus.Closed,
        node: 'El Sauce',
        olt: 'OLT0_X15_FRANCISCO_MOREYRA',
        closingAdvisor: 'Kenneth N.',
        eventEndDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        rootCause: 'Corte de Fibra',
        badPraxis: false,
        solution: 'Fusión de Fibra',
        eventResponsible: 'Equipo de Campo',
    },
    {
        id: 'st22',
        ticketId: 't23',
        code: 'W_CR_000023_R_1',
        cto: 'CTO-MI-018',
        card: '2',
        port: '4',
        city: 'Surquillo',
        clientCount: 13,
        eventStartDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Paul C.',
        status: SubticketStatus.Pending,
        node: 'Mirables',
        olt: 'OLT0_X15_REP_PANAMA',
    },
    {
        id: 'st23',
        ticketId: 't23',
        code: 'W_CR_000023_R_2',
        cto: 'CTO-MI-019',
        card: '2',
        port: '5',
        city: 'Surquillo',
        clientCount: 6,
        eventStartDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        reportedToPextDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        creator: 'Paul C.',
        status: SubticketStatus.Pending,
        node: 'Mirables',
        olt: 'OLT0_X15_REP_PANAMA',
    },
];

export const initialUploadedData: UploadedRecord[] = [
    {
        id: 'up1',
        fecha: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '71234567',
        sn: 'SN-112233',
        codPedido: 'P-987654',
        departamento: 'Lima',
        distrito: 'La Victoria',
        tipoCaja: 'NAP',
        cto: 'CTO-0203-LA-NE', // Matches subticket st1
        servicio: 'Internet 100Mbps',
    },
    {
        id: 'up2',
        fecha: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Suspendido',
        numDoc: '78901234',
        sn: 'SN-445566',
        codPedido: 'P-987655',
        departamento: 'Ancash',
        distrito: 'Chimbote',
        tipoCaja: 'CTO',
        cto: 'CTO-9999-AN-CH', // No match
        servicio: 'Internet 50Mbps',
    },
    {
        id: 'up3',
        fecha: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '71112233',
        sn: 'SN-778899',
        codPedido: 'P-987656',
        departamento: 'Lima',
        distrito: 'Miraflores',
        tipoCaja: 'CTO',
        cto: 'CTO-0101-NY-NE', // Matches subticket st3
        servicio: 'Internet 200Mbps',
    },
    {
        id: 'up4',
        fecha: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '72345678',
        sn: 'SN-AB12CD',
        codPedido: 'P-112233',
        departamento: 'Lima',
        distrito: 'Lince',
        tipoCaja: 'CTO',
        cto: 'CTO-LN-001', // Matches st4
        servicio: 'Fibra 300Mbps',
    },
    {
        id: 'up5',
        fecha: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Baja',
        numDoc: '73456789',
        sn: 'SN-EF45GH',
        codPedido: 'P-445566',
        departamento: 'Lima',
        distrito: 'San Borja',
        tipoCaja: 'CTO',
        cto: 'CTO-FM-002', // Matches st5
        servicio: 'Internet 150Mbps',
    },
    {
        id: 'up6',
        fecha: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '74567890',
        sn: 'SN-IJ78KL',
        codPedido: 'P-778899',
        departamento: 'Arequipa',
        distrito: 'Yanahuara',
        tipoCaja: 'NAP',
        cto: 'CTO-XYZ-123', // No match
        servicio: 'TV Avanzada',
    },
    {
        id: 'up7',
        fecha: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Suspendido',
        numDoc: '75678901',
        sn: 'SN-MN01OP',
        codPedido: 'P-001122',
        departamento: 'Lima',
        distrito: 'Barranco',
        tipoCaja: 'CTO',
        cto: 'CTO-BA-003', // Matches st6
        servicio: 'Internet 100Mbps',
    },
    {
        id: 'up8',
        fecha: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '76789012',
        sn: 'SN-QR23ST',
        codPedido: 'P-334455',
        departamento: 'Lima',
        distrito: 'San Luis',
        tipoCaja: 'NAP',
        cto: 'NAP-SL-001', // Matches st7
        servicio: 'Dúo Internet + TV',
    },
    {
        id: 'up9',
        fecha: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '77890123',
        sn: 'SN-UV45WX',
        codPedido: 'P-667788',
        departamento: 'La Libertad',
        distrito: 'Trujillo',
        tipoCaja: 'CTO',
        cto: 'CTO-ABC-456', // No match
        servicio: 'Internet 500Mbps',
    },
    {
        id: 'up10',
        fecha: new Date().toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '78901234',
        sn: 'SN-YZ67ZA',
        codPedido: 'P-990011',
        departamento: 'Lima',
        distrito: 'La Molina',
        tipoCaja: 'CTO',
        cto: 'CTO-LA-004', // Matches st8
        servicio: 'Internet 1Gbps',
    },
    {
        id: 'up11',
        fecha: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '79012345',
        sn: 'SN-BC89DE',
        codPedido: 'P-223344',
        departamento: 'Lima',
        distrito: 'San Isidro',
        tipoCaja: 'CTO',
        cto: 'CTO-RP-005', // Matches st9
        servicio: 'Internet 200Mbps',
    },
    {
        id: 'up12',
        fecha: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Baja',
        numDoc: '80123456',
        sn: 'SN-FG01HI',
        codPedido: 'P-556677',
        departamento: 'Lima',
        distrito: 'Jesús María',
        tipoCaja: 'CTO',
        cto: 'CTO-NJ-007', // Matches st11
        servicio: 'Internet 50Mbps',
    },
    {
        id: 'up13',
        fecha: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Suspendido',
        numDoc: '81234567',
        sn: 'SN-JK23LM',
        codPedido: 'P-889900',
        departamento: 'Lima',
        distrito: 'La Molina',
        tipoCaja: 'CTO',
        cto: 'CTO-LM-008', // Matches st12
        servicio: 'Internet 100Mbps',
    },
    {
        id: 'up14',
        fecha: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '82345678',
        sn: 'SN-NO45PQ',
        codPedido: 'P-111222',
        departamento: 'Piura',
        distrito: 'Piura',
        tipoCaja: 'NAP',
        cto: 'CTO-123-DEF', // No match
        servicio: 'Trío Internet+TV+Fono',
    },
    {
        id: 'up15',
        fecha: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '83456789',
        sn: 'SN-RS67TU',
        codPedido: 'P-444555',
        departamento: 'Lima',
        distrito: 'Surco',
        tipoCaja: 'CTO',
        cto: 'CTO-TR-009', // Matches st13
        servicio: 'Internet 300Mbps',
    },
    {
        id: 'up16',
        fecha: new Date(Date.now() - 1 * 12 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '84567890',
        sn: 'SN-VW89XY',
        codPedido: 'P-777888',
        departamento: 'Lima',
        distrito: 'Pueblo Libre',
        tipoCaja: 'CTO',
        cto: 'CTO-SU-010', // Matches st14
        servicio: 'Internet 150Mbps',
    },
    {
        id: 'up17',
        fecha: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Baja',
        numDoc: '85678901',
        sn: 'SN-ZA01BC',
        codPedido: 'P-000111',
        departamento: 'Lima',
        distrito: 'San Isidro',
        tipoCaja: 'CTO',
        cto: 'CTO-CK-011', // Matches st15
        servicio: 'Internet 500Mbps',
    },
    {
        id: 'up18',
        fecha: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '86789012',
        sn: 'SN-DE23FG',
        codPedido: 'P-333444',
        departamento: 'Lima',
        distrito: 'Chorrillos',
        tipoCaja: 'NAP',
        cto: 'NAP-BV-013', // Matches st17
        servicio: 'Internet 100Mbps',
    },
    {
        id: 'up19',
        fecha: new Date(Date.now() - 1 * 12 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '87890123',
        sn: 'SN-HI45JK',
        codPedido: 'P-666777',
        departamento: 'Lima',
        distrito: 'Villa el Salvador',
        tipoCaja: 'CTO',
        cto: 'CTO-200M-014', // Matches st18
        servicio: 'Internet 200Mbps',
    },
    {
        id: 'up20',
        fecha: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '88901234',
        sn: 'SN-LM67NO',
        codPedido: 'P-999000',
        departamento: 'Ica',
        distrito: 'Ica',
        tipoCaja: 'CTO',
        cto: 'CTO-GHI-789', // No match
        servicio: 'Internet 50Mbps',
    },
    {
        id: 'up21',
        fecha: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Baja',
        numDoc: '89012345',
        sn: 'SN-PQ89RS',
        codPedido: 'P-222333',
        departamento: 'Lima',
        distrito: 'Chorrillos',
        tipoCaja: 'CTO',
        cto: 'CTO-CH2-015', // Matches st19
        servicio: 'Internet 100Mbps',
    },
    {
        id: 'up22',
        fecha: new Date().toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '90123456',
        sn: 'SN-TU01UV',
        codPedido: 'P-555666',
        departamento: 'Lima',
        distrito: 'Independencia',
        tipoCaja: 'CTO',
        cto: 'CTO-GU-016', // Matches st20
        servicio: 'Internet 150Mbps',
    },
    {
        id: 'up23',
        fecha: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        estadoCuenta: 'Activo',
        numDoc: '91234567',
        sn: 'SN-WX23YZ',
        codPedido: 'P-888999',
        departamento: 'Lima',
        distrito: 'Villa María del Triunfo',
        tipoCaja: 'NAP',
        cto: 'NAP-ES-017', // Matches st21
        servicio: 'Internet 300Mbps',
    }
];


// SVG Icons as JSX components
export const ICONS = {
    dashboard: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V10"/><path d="M18 20V4"/><path d="M6 20V16"/></svg>,
    ticket: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z"/><path d="M13 5v2"/><path d="M13 17v2"/><path d="M13 11v2"/></svg>,
    mail: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>,
    sql: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5V19A9 3 0 0 0 21 19V5"/><path d="M3 12A9 3 0 0 0 21 12"/></svg>,
    archive: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="20" height="5" x="2" y="3" rx="1"/><path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/></svg>,
    upload: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>,
    users: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>,
    bell: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/></svg>,
    plus: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>,
    minus: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="5" y1="12" x2="19" y2="12"></line></svg>,
    chevronDown: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m6 9 6 6 6-6"/></svg>,
    chevronUp: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m18 15-6-6-6 6"/></svg>,
    x: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>,
    edit: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"/><path d="m15 5 4 4"/></svg>,
    trash: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 6h18"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>,
    file: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/></svg>,
    lock: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>,
    unlock: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 9.9-1"/><path d="M21 7v4"/></svg>,
    restore: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/></svg>,
    sparkles: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/><path d="M18 13a6 6 0 0 0-9-9"/><path d="M6 21A6 6 0 0 0 15 12 9 9 0 0 1 6 21"/></svg>,
    shirt: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z"/></svg>,
    sun: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m4.93 19.07 1.41-1.41"/><path d="m17.66 6.34 1.41-1.41"/></svg>,
    moon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg>,
    check: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>,
    grip: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="9" cy="12" r="1"></circle><circle cx="9" cy="5" r="1"></circle><circle cx="9" cy="19" r="1"></circle><circle cx="15" cy="12" r="1"></circle><circle cx="15" cy="5" r="1"></circle><circle cx="15" cy="19" r="1"></circle></svg>,
    'refresh-cw': <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M3 12a9 9 0 0 1 9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/></svg>,
    'bar-chart': <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="20" x2="12" y2="10" /><line x1="18" y1="20" x2="18" y2="4" /><line x1="6" y1="20" x2="6" y2="16" /></svg>,
    'file-output': <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10.4 12.6a2 2 0 1 1 3.2 2.4"/><path d="M16 22h2a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v18"/><path d="M4 22h2"/><path d="M10 22h2"/></svg>,
    settings: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 0 2l-.15.08a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1 0-2l.15.08a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/></svg>,
    box: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>,
    mapPin: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>,
    calendar: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line x1="16" x2="16" y1="2" y2="6"/><line x1="8" x2="8" y1="2" y2="6"/><line x1="3" x2="21" y1="10" y2="10"/></svg>,
};
